name = "amazing_final_project"
uuid = "dde67b72-a4f2-4812-84c0-e08de78f3b84"
authors = ["Zijia-Liu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
